# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import banking_pb2 as banking__pb2


class BankingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCustomerEvents = channel.unary_unary(
                '/banking.BankingService/ProcessCustomerEvents',
                request_serializer=banking__pb2.CustomerProcess.SerializeToString,
                response_deserializer=banking__pb2.CustomerEvent.FromString,
                )
        self.ProcessBranchEvents = channel.unary_unary(
                '/banking.BankingService/ProcessBranchEvents',
                request_serializer=banking__pb2.BranchProcess.SerializeToString,
                response_deserializer=banking__pb2.BranchEvent.FromString,
                )


class BankingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessCustomerEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessBranchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCustomerEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCustomerEvents,
                    request_deserializer=banking__pb2.CustomerProcess.FromString,
                    response_serializer=banking__pb2.CustomerEvent.SerializeToString,
            ),
            'ProcessBranchEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBranchEvents,
                    request_deserializer=banking__pb2.BranchProcess.FromString,
                    response_serializer=banking__pb2.BranchEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.BankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BankingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessCustomerEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.BankingService/ProcessCustomerEvents',
            banking__pb2.CustomerProcess.SerializeToString,
            banking__pb2.CustomerEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessBranchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/banking.BankingService/ProcessBranchEvents',
            banking__pb2.BranchProcess.SerializeToString,
            banking__pb2.BranchEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
