# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\"#\n\x0cQueryRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\"4\n\x0e\x44\x65positRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x02\"5\n\x0fWithdrawRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x02\"@\n\x0f\x42\x61nkingResponse\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x18\n\x10response_message\x18\x02 \x01(\t\"@\n\rCustomerEvent\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x12\n\x05money\x18\x02 \x01(\x02H\x00\x88\x01\x01\x42\x08\n\x06_money2\x88\x02\n\x0e\x42\x61nkingService\x12(\n\x05Query\x12\r.QueryRequest\x1a\x10.BankingResponse\x12,\n\x07\x44\x65posit\x12\x0f.DepositRequest\x1a\x10.BankingResponse\x12.\n\x08Withdraw\x12\x10.WithdrawRequest\x1a\x10.BankingResponse\x12\x35\n\x10PropagateDeposit\x12\x0f.DepositRequest\x1a\x10.BankingResponse\x12\x37\n\x11PropagateWithdraw\x12\x10.WithdrawRequest\x1a\x10.BankingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_QUERYREQUEST']._serialized_start=17
  _globals['_QUERYREQUEST']._serialized_end=52
  _globals['_DEPOSITREQUEST']._serialized_start=54
  _globals['_DEPOSITREQUEST']._serialized_end=106
  _globals['_WITHDRAWREQUEST']._serialized_start=108
  _globals['_WITHDRAWREQUEST']._serialized_end=161
  _globals['_BANKINGRESPONSE']._serialized_start=163
  _globals['_BANKINGRESPONSE']._serialized_end=227
  _globals['_CUSTOMEREVENT']._serialized_start=229
  _globals['_CUSTOMEREVENT']._serialized_end=293
  _globals['_BANKINGSERVICE']._serialized_start=296
  _globals['_BANKINGSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
