# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import banking_pb2
import banking_pb2 as banking__pb2


class BankingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/BankingService/Query',
                request_serializer=banking__pb2.QueryRequest.SerializeToString,
                response_deserializer=banking__pb2.BankingResponse.FromString,
                )
        self.Deposit = channel.unary_unary(
                '/BankingService/Deposit',
                request_serializer=banking__pb2.DepositRequest.SerializeToString,
                response_deserializer=banking__pb2.BankingResponse.FromString,
                )
        self.Withdraw = channel.unary_unary(
                '/BankingService/Withdraw',
                request_serializer=banking__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=banking__pb2.BankingResponse.FromString,
                )
        self.PropagateDeposit = channel.unary_unary(
                '/BankingService/PropagateDeposit',
                request_serializer=banking__pb2.DepositRequest.SerializeToString,
                response_deserializer=banking__pb2.BankingResponse.FromString,
                )
        self.PropagateWithdraw = channel.unary_unary(
                '/BankingService/PropagateWithdraw',
                request_serializer=banking__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=banking__pb2.BankingResponse.FromString,
                )


class BankingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        # context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        # context.set_details('Method not implemented!')
        # raise NotImplementedError('Method not implemented!')
        print("logic is here")
        response = banking_pb2.BankingResponse()
        response.balance = 500  # Replace with actual balance logic
        return response


    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateDeposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PropagateWithdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=banking__pb2.QueryRequest.FromString,
                    response_serializer=banking__pb2.BankingResponse.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=banking__pb2.DepositRequest.FromString,
                    response_serializer=banking__pb2.BankingResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=banking__pb2.WithdrawRequest.FromString,
                    response_serializer=banking__pb2.BankingResponse.SerializeToString,
            ),
            'PropagateDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateDeposit,
                    request_deserializer=banking__pb2.DepositRequest.FromString,
                    response_serializer=banking__pb2.BankingResponse.SerializeToString,
            ),
            'PropagateWithdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.PropagateWithdraw,
                    request_deserializer=banking__pb2.WithdrawRequest.FromString,
                    response_serializer=banking__pb2.BankingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BankingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankingService/Query',
            banking__pb2.QueryRequest.SerializeToString,
            banking__pb2.BankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankingService/Deposit',
            banking__pb2.DepositRequest.SerializeToString,
            banking__pb2.BankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankingService/Withdraw',
            banking__pb2.WithdrawRequest.SerializeToString,
            banking__pb2.BankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PropagateDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankingService/PropagateDeposit',
            banking__pb2.DepositRequest.SerializeToString,
            banking__pb2.BankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PropagateWithdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BankingService/PropagateWithdraw',
            banking__pb2.WithdrawRequest.SerializeToString,
            banking__pb2.BankingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
