# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\x12\x07\x62\x61nking\"\xaf\x01\n\rCustomerEvent\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x34\n\nevent_type\x18\x02 \x01(\x0e\x32 .banking.CustomerEvent.EventType\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\x05\"1\n\tEventType\x12\t\n\x05QUERY\x10\x00\x12\x0b\n\x07\x44\x45POSIT\x10\x01\x12\x0c\n\x08WITHDRAW\x10\x02\"\xb2\x01\n\x0b\x42ranchEvent\x12\x11\n\tbranch_id\x18\x01 \x01(\t\x12\x32\n\nevent_type\x18\x02 \x01(\x0e\x32\x1e.banking.BranchEvent.EventType\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\x05\":\n\tEventType\x12\x15\n\x11PROPAGATE_DEPOSIT\x10\x00\x12\x16\n\x12PROPAGATE_WITHDRAW\x10\x01\"E\n\x0f\x43ustomerProcess\x12\n\n\x02id\x18\x01 \x01(\t\x12&\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x16.banking.CustomerEvent\"4\n\rBranchProcess\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0finitial_balance\x18\x02 \x01(\x05\x32\xa0\x01\n\x0e\x42\x61nkingService\x12I\n\x15ProcessCustomerEvents\x12\x18.banking.CustomerProcess\x1a\x16.banking.CustomerEvent\x12\x43\n\x13ProcessBranchEvents\x12\x16.banking.BranchProcess\x1a\x14.banking.BranchEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CUSTOMEREVENT']._serialized_start=27
  _globals['_CUSTOMEREVENT']._serialized_end=202
  _globals['_CUSTOMEREVENT_EVENTTYPE']._serialized_start=153
  _globals['_CUSTOMEREVENT_EVENTTYPE']._serialized_end=202
  _globals['_BRANCHEVENT']._serialized_start=205
  _globals['_BRANCHEVENT']._serialized_end=383
  _globals['_BRANCHEVENT_EVENTTYPE']._serialized_start=325
  _globals['_BRANCHEVENT_EVENTTYPE']._serialized_end=383
  _globals['_CUSTOMERPROCESS']._serialized_start=385
  _globals['_CUSTOMERPROCESS']._serialized_end=454
  _globals['_BRANCHPROCESS']._serialized_start=456
  _globals['_BRANCHPROCESS']._serialized_end=508
  _globals['_BANKINGSERVICE']._serialized_start=511
  _globals['_BANKINGSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
